### ISSUE TITLE
NoMethodError for `register_plugin'

### ISSUE THREAD

**Issue by seitensei** [rom-rb/rom-roda#3]
I'm unable to get rom-roda working with a combination of roda 2.70 and rom 0.9.1 under Ruby 2.2.1 on OS X 10.10.5. puma appears to be a non-issue, since I didn't have any luck under thin either.

Code that I'm invoking:
```ruby
require 'rom'
require 'rom-roda'
require 'rom-sql'


class AppCore < Roda
  plugin :rom, {
    default: {
      setup: [:sql, 'sqlite::memory'],
      plugins: [:auto_registration]
    },
    load_path: 'models'
  }
  plugin :render
  plugin :assets
  plugin :view_subdirs
  plugin :multi_route
  Dir['./routes/*.rb'].each{|f| require f}

  route do |r|
    r.multi_route
  end

  Dir['./helpers/*.rb'].each{|f| require f}

end
```
CLI:
```
$ bundle exec puma                                                                                                                         [10:12:38]
Puma starting in single mode...
* Version 2.14.0 (ruby 2.2.1-p85), codename: Fuchsia Friday
* Min threads: 0, max threads: 16
* Environment: development
! Unable to load application: NoMethodError: undefined method `register_plugin' for Roda::RodaPlugins:Module
/Users/thanhn/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rom-roda-0.2.0/lib/rom-roda.rb:7:in `<module:RodaPlugins>': undefined method `register_plugin' for Roda::RodaPlugins:Module (NoMethodError)
	from /Users/thanhn/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rom-roda-0.2.0/lib/rom-roda.rb:6:in `<class:Roda>'
	from /Users/thanhn/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rom-roda-0.2.0/lib/rom-roda.rb:5:in `<top (required)>'
	from /Users/thanhn/Projects/Ruby/gvclocker/gvclocker.rb:2:in `require'
	from /Users/thanhn/Projects/Ruby/gvclocker/gvclocker.rb:2:in `<top (required)>'
	from config.ru:1:in `require'
	from config.ru:1:in `block in <main>'
	from /Users/thanhn/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/thanhn/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /Users/thanhn/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from /Users/thanhn/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/thanhn/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from /Users/thanhn/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/puma-2.14.0/lib/puma/configuration.rb:143:in `load_rackup'
	from /Users/thanhn/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/puma-2.14.0/lib/puma/configuration.rb:96:in `app'
	from /Users/thanhn/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/puma-2.14.0/lib/puma/runner.rb:113:in `load_and_bind'
	from /Users/thanhn/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/puma-2.14.0/lib/puma/single.rb:79:in `run'
	from /Users/thanhn/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/puma-2.14.0/lib/puma/cli.rb:215:in `run'
	from /Users/thanhn/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/puma-2.14.0/bin/puma:10:in `<top (required)>'
	from /Users/thanhn/.rbenv/versions/2.2.1/bin/puma:23:in `load'
	from /Users/thanhn/.rbenv/versions/2.2.1/bin/puma:23:in `<main>'
```
